server:
  port: 8002
spring:
  application:
    name: order-service
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
shipment-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8001,localhost:8003,localhost:8004
    ServerListRefreshInterval: 15000
    
    